New: when lex/yacc type is not recognized, revert to flex/bison patch files

diff --git a/ddd/lextoC b/ddd/lextoC
--- a/ddd/lextoC
+++ b/ddd/lextoC
@@ -64,11 +64,6 @@ if [ $? = 0 ]; then
   exit 1
 fi
 
-grep '@(#).*com/lib/l/ncform' lex.yy.c > /dev/null 
-if [ $? = 0 ]; then
-  lexpar=flex
-fi
-
 grep '@(#)ncform.*SMI' lex.yy.c > /dev/null
 if [ $? = 0 ]; then
   lexpar=sun
@@ -80,8 +75,8 @@ if [ $? = 0 ]; then
 fi
 
 if [ "$lexpar" = "" ]; then
-  echo "$this: cannot determine lex type -- fix lex.yy.c manually" >&2
-  exit 1
+  echo "$this: cannot determine lex type -- reverting to flex" >&2
+  lexpar=flex
 fi
   
 script=$path/$this.$lexpar
diff --git a/ddd/yacctoC b/ddd/yacctoC
--- a/ddd/yacctoC
+++ b/ddd/yacctoC
@@ -81,19 +81,14 @@ for file in y.tab.c y.tab.h; do
       yaccpar=sun
     fi
 
-    grep '@(#).*com/cmd/lang/yacc/yaccpar' $file > /dev/null     
-    if [ $? = 0 ]; then
-      yaccpar=bison
-    fi
-
     grep 'Bison parser' $file > /dev/null
     if [ $? = 0 ]; then
       yaccpar=bison
     fi
   
     if [ "$yaccpar" = "" ]; then
-      echo "$this: cannot determine yaccpar type -- fix y.tab.c manually" >&2
-      exit 1
+      echo "$this: cannot determine yaccpar type -- reverting to bison" >&2
+      yaccpar=bison
     fi
     
     script=$path/$this.$yaccpar
